name: macOS app build (PyInstaller)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14  # Apple Silicon; nếu muốn build bản Intel thì đổi thành macos-13

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pygame pyinstaller

      - name: Build .app
        run: |
          pyinstaller --windowed --name "HelloKittyHeart3D" main.py
          ls -la dist

      - name: Zip app bundle
        run: |
          cd dist
          /usr/bin/ditto -c -k --sequesterRsrc --keepParent HelloKittyHeart3D.app HelloKittyHeart3D.zip
          ls -la

      - name: Upload artifact
        uses: actions/upload-arti
